# Generated by Django 2.1 on 2018-08-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20180813_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicenode',
            name='number',
            field=models.IntegerField(help_text='Enter the order number of this practice node.', null=True),
        ),
    ]
