# Generated by Django 2.1 on 2018-08-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_auto_20180815_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='node',
            new_name='practice',
        ),
    ]
