# Generated by Django 2.1 on 2018-08-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0012_auto_20180816_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
