# Generated by Django 3.0.3 on 2020-02-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0015_auto_20180818_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Enter the title for this article.', max_length=60)),
                ('body', models.TextField(help_text='Enter the body for this article.')),
            ],
        ),
    ]
