# Generated by Django 3.0.3 on 2020-02-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0016_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(default='Body', help_text='Enter the body for this article.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Title', help_text='Enter the title for this article.', max_length=60, primary_key=True, serialize=False),
        ),
    ]
